/**
 * This is generic and not fully featured, but it is a good
 * starting point for testing your plugins. Adjust as needed.
 */
export default {
  author_association: "NONE",
  closed_at: null,
  comments: 0,
  comments_url: "",
  created_at: new Date().toISOString(),
  events_url: "",
  html_url: "https://github.com/ubiquity/test-repo/issues/1",
  id: 1,
  labels_url: "",
  locked: false,
  milestone: null,
  node_id: "1",
  owner: "ubiquity",
  number: 1,
  repository_url: "https://github.com/ubiquity/test-repo",
  state: "open",
  title: "issue",
  updated_at: "",
  url: "",
  user: null,
  repo: "test-repo",
  labels: [
    {
      name: "Price: 25 USD",
    },
    {
      name: "Time: <1 Hour",
    },
    {
      name: "Priority: 1 (Normal)",
    },
  ],
  body: "body",
  assignee: {
    login: "",
    avatar_url: "",
    email: "undefined",
    events_url: "",
    followers_url: "",
    following_url: "",
    gists_url: "",
    gravatar_id: null,
    html_url: "",
    id: 1,
    name: "undefined",
    node_id: "",
    organizations_url: "",
    received_events_url: "",
    repos_url: "",
    site_admin: false,
    starred_at: "",
    starred_url: "",
    subscriptions_url: "",
    type: "",
    url: "",
  },
};
